name: Secrets Practice
on: [push]

jobs:
    secret-test:
        runs-on: ubuntu-latest
        steps:
            - name: Show secret
              run: echo "The secret message is: ${{ secrets.GREETING }}"
