name: Environment Practice
on: [push]

env:
  COMPANY: "GitHub"

jobs:
  test-env:
    runs-on: ubuntu-latest
    env:
      PROJECT: "Actions Learning"
    steps:
      - name: Show variables
        env:
          TRAINER: "Your Name"
        run: |
          echo "Welcome to $COMPANY $PROJECT training by $TRAINER"
          echo "This workflow was triggered by $GITHUB_ACTOR"
